name: My Java App Workflow (Upstream)

on: 
  workflow_dispatch:
    inputs:
      UploadToPackage:
        description: "Upload to Maven Package"
        required: true
        default: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout application
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Application
      run: mvn clean package

    # - name: Publish to GitHub Packages
    #   if: ${{ github.event.inputs.UploadToPackage == 'true' }}
    #   env:
    #     USERNAME: 'charanaswanth'
    #     TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   run: mvn deploy -s settings.xml
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: my-java-application-1.0-SNAPSHOT.jar
        path: target/my-java-application-1.0-SNAPSHOT.jar
