name: My Java App Workflow (Selfhosted-Windows)

on: 
  workflow_dispatch:
    inputs:
      UploadToPackage:
        description: "Upload to Maven Package"
        required: true
        default: false
        type: boolean
jobs:
  build:
    runs-on: Windows

    steps:
    - name: Checkout application
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Application
      run: mvn clean package -DskipTests

    - name: Publish to GitHub Packages
      if: ${{ github.event.inputs.UploadToPackage == 'true' }}
      env:
        USERNAME: 'charanaswanth'
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: mvn deploy -DskipTests -s settings.xml
