name: My Java App Workflow (Selfhosted-Nexus)

on: 
  workflow_dispatch:
    inputs:
      UploadToPackage:
        description: "Upload to Nexus"
        required: true
        default: false
        type: boolean
jobs:
  build:
    runs-on: Linux

    steps:
    - name: Checkout application
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Application
      run: mvn clean package

    - name: Publish to GitHub Packages
      if: ${{ github.event.inputs.UploadToPackage == 'true' }}
      env:
        USERNAME: ${{ secrets.NEXUS_USERNAME }}
        PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: mvn deploy -s settingsNexus