name: My Java App Workflow (Docker)

on: 
  workflow_dispatch
jobs:
  build:
    runs-on: Linux

    steps:
    - name: Checkout application
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build Application
      run: mvn clean package

    - name: Github registry login
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: 'charanaswanth'
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run:
        docker build -t ghcr.io/${{ github.repository }}/myjavapp:latest .

    - name: Push Docker image
      run:
          docker push ghcr.io/${{ github.repository }}/myjavapp:latest